'use server'

import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { createClient } from '../../../lib/supabase-server'

const num = (formData: FormData, key: string, fallback = 0) => {
  const value = Number(formData.get(key) ?? fallback)
  return Number.isFinite(value) ? value : fallback
}

const text = (formData: FormData, key: string) => String(formData.get(key) || '').trim()


async function assertAdmin() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')
  const { data: profile } = await supabase.from('profiles').select('role').eq('user_id', user.id).maybeSingle()
  if (profile?.role !== 'AMMINISTRATORE') redirect('/dashboard')
  return { supabase, user }
}

const articlePayload = (formData: FormData) => {
  const quantity = num(formData, 'quantity_purchased')
  return {
    purchase_date: text(formData, 'purchase_date') || new Date().toISOString().slice(0, 10),
    origin: text(formData, 'origin') || 'GIAPPONE',
    article_type: text(formData, 'article_type') || 'ALTRO',
    seller: text(formData, 'seller') || null,
    series: text(formData, 'series') || null,
    detail: text(formData, 'detail') || null,
    quantity_purchased: quantity,
    currency: text(formData, 'currency') || 'EUR',
    unit_price_foreign: num(formData, 'unit_price_foreign'),
    exchange_rate: num(formData, 'exchange_rate', 1),
    commission_type: text(formData, 'commission_mode') || 'FIXED',
    commission_cost: num(formData, 'commission_cost'),
    commission_percent: num(formData, 'commission_percent'),
    commission_currency: text(formData, 'commission_currency') || 'EUR',
    commission_exchange_rate: num(formData, 'commission_exchange_rate', 1),
    customs_type: text(formData, 'customs_mode') || 'PERCENT',
    customs_cost: num(formData, 'customs_cost'),
    customs_percent: num(formData, 'customs_percent'),
    customs_currency: text(formData, 'customs_currency') || 'EUR',
    customs_exchange_rate: num(formData, 'customs_exchange_rate', 1),
    shipping_type: text(formData, 'shipping_mode') || 'FIXED',
    shipping_cost: num(formData, 'shipping_cost'),
    shipping_percent: num(formData, 'shipping_percent'),
    shipping_currency: text(formData, 'shipping_currency') || 'EUR',
    shipping_exchange_rate: num(formData, 'shipping_exchange_rate', 1),
    // I campi total_cost_eur e unit_cost_eur sono GENERATED BY DATABASE: non vanno inviati nell'INSERT/UPDATE.
    accessory_cost_eur: 0,
    // photo_url viene gestito separatamente durante creazione/modifica
    notes: text(formData, 'notes') || null,
    status: text(formData, 'status') || 'IN_ARRIVO',
  }
}

export async function createArticle(formData: FormData) {
  const { supabase, user } = await assertAdmin()
  const quantity = num(formData, 'quantity_purchased')
  if (quantity <= 0) redirect('/admin/articoli/nuovo?error=La quantità deve essere maggiore di zero.')

  const photo = formData.get('photo')
  const directPhotoUrl = text(formData, 'photo_url')
  if (photo instanceof File && photo.size > 0) {
    if (!photo.type.startsWith('image/')) redirect('/admin/articoli/nuovo?error=Il file selezionato non è una foto valida.')
    if (photo.size > 8 * 1024 * 1024) redirect('/admin/articoli/nuovo?error=La foto supera il limite di 8 MB.')
  }

  const payload = articlePayload(formData)
  const saleEnabled = text(formData, 'sale_enabled') === 'on'
  const saleCustomerCode = saleEnabled ? text(formData, 'sale_customer_code').toUpperCase() : ''
  const saleQuantity = saleEnabled ? num(formData, 'sale_quantity') : 0
  const salePrice = saleEnabled ? num(formData, 'sale_price') : 0
  const movementDate = text(formData, 'purchase_date') || new Date().toISOString().slice(0, 10)
  const exchangeRate = Number(payload.exchange_rate || 0)
  const accessoryRates = [payload.commission_exchange_rate, payload.customs_exchange_rate, payload.shipping_exchange_rate].map(Number)
  if (!Number.isFinite(exchangeRate) || exchangeRate <= 0 || accessoryRates.some((value) => !Number.isFinite(value) || value <= 0)) {
    redirect('/admin/articoli/nuovo?error=Uno o più cambi valuta non sono validi.')
  }

  if (saleEnabled && (!saleCustomerCode || !saleQuantity || saleQuantity <= 0 || !salePrice || salePrice <= 0 || saleQuantity > quantity)) {
    redirect('/admin/articoli/nuovo?error=Dati della vendita contestuale non validi.')
  }

  type ArticleResult = {
    id: string
    article_code: string
    quantity_purchased: number
    total_cost_eur: number | null
    status: string
  }

  let article: ArticleResult | null = null

  // Percorso principale: RPC transazionale. La colonna article_type viene gestita
  // all'interno del database e non dipende dalla schema cache della tabella articles.
  const rpcResult = await supabase.rpc('admin_create_article', { p_article: payload })

  if (rpcResult.data) {
    article = rpcResult.data as ArticleResult
  } else {
    // Fallback compatibile con una eventuale RPC non disponibile.
    // Non inviamo article_type direttamente perché la schema cache REST può essere indietro;
    // in questo percorso il database userà il default ALTRO.
    const fallbackPayload = { ...payload } as Record<string, unknown>
    delete fallbackPayload.article_type

    const { data: directArticle, error: directError } = await supabase
      .from('articles')
      .insert(fallbackPayload)
      .select('id,article_code,quantity_purchased,total_cost_eur,status')
      .single()

    if (directError || !directArticle) {
      redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(rpcResult.error?.message || directError?.message || 'Impossibile registrare l’articolo.')}`)
    }

    const { error: movementError } = await supabase.from('movements').insert({
      movement_type: 'ARTICOLO',
      reference_id: directArticle.id,
      reference_code: directArticle.article_code,
      article_id: directArticle.id,
      quantity: Number(directArticle.quantity_purchased || 0),
      total_amount_eur: Number(directArticle.total_cost_eur || 0),
      description: 'Creazione articolo',
      operator_user_id: user.id,
      movement_at: `${payload.purchase_date}T00:00:00`,
    })

    if (movementError) {
      await supabase.from('movements').delete().eq('article_id', directArticle.id).eq('movement_type', 'ARTICOLO')
      await supabase.from('articles').delete().eq('id', directArticle.id)
      redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Registrazione movimento non riuscita: ${movementError.message}`)}`)
    }

    article = directArticle as ArticleResult
  }

  if (!article) {
    redirect('/admin/articoli/nuovo?error=Impossibile registrare l’articolo.')
  }

  if (photo instanceof File && photo.size > 0) {
    if (!photo.type.startsWith('image/')) redirect('/admin/articoli/nuovo?error=Il file selezionato non è una foto valida.')
    if (photo.size > 8 * 1024 * 1024) redirect('/admin/articoli/nuovo?error=La foto supera il limite di 8 MB.')
    const extension = photo.name.split('.').pop()?.toLowerCase() || 'jpg'
    const path = `${article.id}-${Date.now()}.${extension}`
    const { error: uploadError } = await supabase.storage.from('article-photos').upload(path, photo, { contentType: photo.type, upsert: true })
    if (uploadError) {
      await supabase.from('movements').delete().eq('article_id', article.id)
      await supabase.from('articles').delete().eq('id', article.id)
      redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Caricamento foto non riuscito: ${uploadError.message}. Verifica che l'app punti al progetto Supabase corretto e che il bucket article-photos sia disponibile.`)}`)
    }
    const { data: publicData } = supabase.storage.from('article-photos').getPublicUrl(path)
    const { error: photoUpdateError } = await supabase.from('articles').update({ photo_url: publicData.publicUrl }).eq('id', article.id)
    if (photoUpdateError) {
      await supabase.storage.from('article-photos').remove([path])
      await supabase.from('movements').delete().eq('article_id', article.id)
      await supabase.from('articles').delete().eq('id', article.id)
      redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Salvataggio foto non riuscito: ${photoUpdateError.message}`)}`)
    }
  } else if (directPhotoUrl) {
    await supabase.from('articles').update({ photo_url: directPhotoUrl }).eq('id', article.id)
  }

  if (saleEnabled) {
    const saleRpc = await supabase.rpc('register_article_sales', {
      p_customer_code: saleCustomerCode,
      p_lines: [{ article_id: article.id, quantity: saleQuantity, price: salePrice }],
      p_movement_date: movementDate,
    })

    if (saleRpc.error) {
      const { data: customer, error: customerError } = await supabase
        .from('customers')
        .select('id,customer_code')
        .ilike('customer_code', saleCustomerCode)
        .maybeSingle()

      if (customerError || !customer) {
        await supabase.from('movements').delete().eq('article_id', article.id)
        await supabase.from('articles').delete().eq('id', article.id)
        redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(customerError?.message || `Codice cliente non trovato: ${saleCustomerCode}`)}`)
      }

      const { data: mailbox, error: mailboxError } = await supabase
        .from('mailboxes')
        .select('id')
        .eq('customer_id', customer.id)
        .maybeSingle()

      if (mailboxError) {
        await supabase.from('movements').delete().eq('article_id', article.id)
        await supabase.from('articles').delete().eq('id', article.id)
        redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(mailboxError.message)}`)
      }

      const { error: directSaleError } = await supabase.from('movements').insert({
        mailbox_id: mailbox?.id || null,
        movement_type: 'VENDITA',
        article_id: article.id,
        quantity: saleQuantity,
        unit_price_eur: salePrice,
        total_amount_eur: saleQuantity * salePrice,
        generic_customer_name: customer.customer_code,
        customer_name: customer.customer_code,
        description: 'Vendita articolo',
        operator_user_id: user.id,
        movement_at: `${movementDate}T00:00:00`,
      })

      if (directSaleError) {
        await supabase.from('movements').delete().eq('article_id', article.id)
        await supabase.from('articles').delete().eq('id', article.id)
        redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Vendita contestuale non registrata: ${directSaleError.message}`)}`)
      }

      if (mailbox?.id) {
        const { error: assignmentError } = await supabase.from('article_assignments').insert({
          article_id: article.id,
          mailbox_id: mailbox.id,
          quantity_assigned: saleQuantity,
          status: 'ATTIVA',
          notes: 'Assegnazione da vendita',
        })

        if (assignmentError) {
          await supabase.from('movements').delete().eq('article_id', article.id)
          await supabase.from('article_assignments').delete().eq('article_id', article.id)
          await supabase.from('articles').delete().eq('id', article.id)
          redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Assegnazione contestuale non registrata: ${assignmentError.message}`)}`)
        }
      }

      const remaining = Number(article.quantity_purchased || 0) - saleQuantity
      const nextStatus = remaining <= 0 ? 'VENDUTO' : (payload.status === 'IN_ARRIVO' ? 'IN_ARRIVO' : 'IN_STOCK')
      const { error: statusError } = await supabase.from('articles').update({ status: nextStatus, updated_at: new Date().toISOString() }).eq('id', article.id)
      if (statusError) {
        await supabase.from('article_assignments').delete().eq('article_id', article.id)
        await supabase.from('movements').delete().eq('article_id', article.id)
        await supabase.from('articles').delete().eq('id', article.id)
        redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Aggiornamento stato articolo non riuscito: ${statusError.message}`)}`)
      }
    }
  }

  revalidatePath('/admin/articoli/archivio')
  revalidatePath('/admin/articoli/nuovo')
  redirect('/admin/articoli/archivio?message=Articolo registrato correttamente.')
}

export async function updateArticle(formData: FormData) {
  const { supabase, user } = await assertAdmin()
  const id = text(formData, 'id')
  if (!id) redirect('/admin/articoli?error=ID articolo mancante.')

  const returnToArchive = text(formData, 'return_to') === 'archive'
  const returnPath = returnToArchive ? '/admin/articoli/archivio' : `/admin/articoli/${id}`
  const fail = (message: string): never => redirect(`${returnPath}?error=${encodeURIComponent(message)}`)
  const succeed = (): never => redirect(returnToArchive
    ? '/admin/articoli/archivio?message=Articolo modificato correttamente.'
    : `/admin/articoli/${id}?message=Modifiche salvate correttamente.`)

  const quantity = num(formData, 'quantity_purchased')
  if (quantity <= 0) fail('La quantità deve essere maggiore di zero.')

  const payload = articlePayload(formData)
  // La tabella reale usa *_mode (non *_type) e i costi accessori sono
  // calcolati dal trigger del database, quindi non vanno azzerati dal form.
  const {
    commission_type,
    customs_type,
    shipping_type,
    accessory_cost_eur: _computedAccessoryCost,
    ...commonPayload
  } = payload
  const updatePayload: Record<string, unknown> = {
    ...commonPayload,
    commission_mode: commission_type,
    customs_mode: customs_type,
    shipping_mode: shipping_type,
  }

  const directPhotoUrl = text(formData, 'photo_url')
  const photo = formData.get('photo')
  let photoPatch: Record<string, string | null> = {}
  if (photo instanceof File && photo.size > 0) {
    if (!photo.type.startsWith('image/') || photo.size > 8 * 1024 * 1024) fail('Foto non valida o superiore a 8 MB.')
    const extension = photo.name.split('.').pop()?.toLowerCase() || 'jpg'
    const path = `${id}-${Date.now()}.${extension}`
    const { error: uploadError } = await supabase.storage.from('article-photos').upload(path, photo, { contentType: photo.type, upsert: true })
    if (uploadError) fail(`Caricamento foto non riuscito: ${uploadError.message}. Verifica che il bucket article-photos sia disponibile.`)
    const { data: publicData } = supabase.storage.from('article-photos').getPublicUrl(path)
    photoPatch = { photo_url: publicData.publicUrl }
  } else if (directPhotoUrl) {
    try { new URL(directPhotoUrl) } catch { fail('Link immagine non valido.') }
    photoPatch = { photo_url: directPhotoUrl }
  }

  const { data: currentArticle, error: currentError } = await supabase
    .from('articles')
    .select('article_code')
    .eq('id', id)
    .maybeSingle()
  if (currentError || !currentArticle) fail(currentError?.message || 'Articolo non trovato.')
  // Conserva il codice letto prima dell'aggiornamento; il fallback all'ID
  // evita che il type-checker consideri currentArticle potenzialmente null.
  const currentArticleCode = currentArticle?.article_code || id

  const { error } = await supabase.from('articles').update({ ...updatePayload, ...photoPatch }).eq('id', id)
  if (error) fail(error.message)

  await supabase.from('movements').insert({
    movement_type: 'MODIFICA',
    reference_id: id,
    reference_code: currentArticleCode,
    article_id: id,
    description: 'Articolo modificato',
    operator_user_id: user.id,
  })

  revalidatePath('/admin/articoli/archivio')
  revalidatePath(`/admin/articoli/${id}`)
  succeed()
}

export async function updateSelectedArticles(formData: FormData) {
  const { supabase, user } = await assertAdmin()
  const ids = String(formData.get('article_ids') || '').split(',').map((x) => x.trim()).filter(Boolean)
  if (ids.length < 2) redirect('/admin/articoli/archivio?error=Per la modifica multipla seleziona almeno due articoli.')

  const rawNumber = (key: string) => {
    const raw = text(formData, key)
    if (!raw) return null
    const value = Number(raw)
    if (!Number.isFinite(value) || value < 0) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(`Valore non valido: ${key}.`)}`)
    return value
  }
  const validCurrency = (value: string) => !value || ['EUR', 'JPY', 'USD'].includes(value)

  const modes = {
    commission: text(formData, 'bulk_commission_mode').toUpperCase(),
    customs: text(formData, 'bulk_customs_mode').toUpperCase(),
    shipping: text(formData, 'bulk_shipping_mode').toUpperCase(),
  }
  for (const [label, mode] of Object.entries(modes)) {
    if (mode && mode !== 'FIXED' && mode !== 'PERCENT') redirect(`/admin/articoli/archivio?error=${encodeURIComponent(`Modalità ${label} non valida.`)}`)
  }

  const values = {
    commissionCost: rawNumber('bulk_commission_cost'),
    commissionPercent: rawNumber('bulk_commission_percent'),
    commissionCurrency: text(formData, 'bulk_commission_currency').toUpperCase(),
    customsCost: rawNumber('bulk_customs_cost'),
    customsPercent: rawNumber('bulk_customs_percent'),
    customsCurrency: text(formData, 'bulk_customs_currency').toUpperCase(),
    shippingCost: rawNumber('bulk_shipping_cost'),
    shippingPercent: rawNumber('bulk_shipping_percent'),
    shippingCurrency: text(formData, 'bulk_shipping_currency').toUpperCase(),
    rateJpy: rawNumber('bulk_rate_jpy'),
    rateUsd: rawNumber('bulk_rate_usd'),
  }

  for (const [label, currency] of [
    ['commission', values.commissionCurrency],
    ['customs', values.customsCurrency],
    ['shipping', values.shippingCurrency],
  ] as Array<[string, string]>) {
    if (!validCurrency(currency)) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(`Valuta ${label} non valida.`)}`)
  }
  if (values.rateJpy !== null && values.rateJpy <= 0) redirect('/admin/articoli/archivio?error=Cambio Yen/€ non valido.')
  if (values.rateUsd !== null && values.rateUsd <= 0) redirect('/admin/articoli/archivio?error=Cambio $/€ non valido.')

  const hasCostEdit = Object.values(modes).some(Boolean)
  const hasRateEdit = values.rateJpy !== null || values.rateUsd !== null
  if (!hasCostEdit && !hasRateEdit) {
    redirect('/admin/articoli/archivio?error=Seleziona almeno un costo o un cambio da modificare.')
  }

  if (modes.commission === 'FIXED' && (values.commissionCost === null || !values.commissionCurrency)) {
    redirect('/admin/articoli/archivio?error=Per la commissione a importo inserisci importo e valuta.')
  }
  if (modes.commission === 'PERCENT' && values.commissionPercent === null) {
    redirect('/admin/articoli/archivio?error=Inserisci la percentuale della commissione.')
  }
  if (modes.customs === 'FIXED' && (values.customsCost === null || !values.customsCurrency)) {
    redirect('/admin/articoli/archivio?error=Per la dogana a importo inserisci importo e valuta.')
  }
  if (modes.customs === 'PERCENT' && values.customsPercent === null) {
    redirect('/admin/articoli/archivio?error=Inserisci la percentuale della dogana.')
  }
  if (modes.shipping === 'FIXED' && (values.shippingCost === null || !values.shippingCurrency)) {
    redirect('/admin/articoli/archivio?error=Per la spedizione a importo inserisci importo e valuta.')
  }
  if (modes.shipping === 'PERCENT' && values.shippingPercent === null) {
    redirect('/admin/articoli/archivio?error=Inserisci la percentuale della spedizione.')
  }

  const { data: currentRows, error: currentRowsError } = await supabase
    .from('articles')
    .select('id,article_code,currency,exchange_rate,commission_mode,commission_cost,commission_percent,commission_currency,commission_exchange_rate,customs_mode,customs_cost,customs_percent,customs_currency,customs_exchange_rate,shipping_mode,shipping_cost,shipping_percent,shipping_currency,shipping_exchange_rate')
    .in('id', ids)

  if (currentRowsError) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(currentRowsError.message)}`)
  if (!currentRows || currentRows.length !== ids.length) redirect('/admin/articoli/archivio?error=Uno o più articoli non sono stati trovati.')

  const rateForCurrency = (currency: string) => {
    if (currency === 'EUR') return 1
    if (currency === 'JPY') return values.rateJpy
    if (currency === 'USD') return values.rateUsd
    return null
  }

  for (const row of currentRows as any[]) {
    const patch: Record<string, unknown> = {}

    const applyAccessory = (
      prefix: 'commission' | 'customs' | 'shipping',
      mode: string,
      cost: number | null,
      percent: number | null,
      currency: string,
    ) => {
      const modeField = `${prefix}_mode`
      const costField = `${prefix}_cost`
      const percentField = `${prefix}_percent`
      const currencyField = `${prefix}_currency`
      if (!mode) return
      patch[modeField] = mode
      if (mode === 'FIXED') {
        patch[costField] = cost
        patch[percentField] = 0
        patch[currencyField] = currency
      } else {
        patch[percentField] = percent
        patch[costField] = 0
      }
    }

    applyAccessory('commission', modes.commission, values.commissionCost, values.commissionPercent, values.commissionCurrency)
    applyAccessory('customs', modes.customs, values.customsCost, values.customsPercent, values.customsCurrency)
    applyAccessory('shipping', modes.shipping, values.shippingCost, values.shippingPercent, values.shippingCurrency)

    // Compatibilità con articoli storici: in precedenti versioni la percentuale
    // poteva essere compilata pur avendo il modo memorizzato come FIXED.
    for (const prefix of ['commission', 'customs', 'shipping'] as const) {
      const modeField = `${prefix}_mode`
      const costField = `${prefix}_cost`
      const percentField = `${prefix}_percent`
      if (
        patch[modeField] === undefined &&
        Number(row[costField] || 0) === 0 &&
        Number(row[percentField] || 0) > 0
      ) {
        patch[modeField] = 'PERCENT'
      }
    }

    const currencyColumns = [
      { currencyField: 'currency', rateField: 'exchange_rate' },
      { currencyField: 'commission_currency', rateField: 'commission_exchange_rate' },
      { currencyField: 'customs_currency', rateField: 'customs_exchange_rate' },
      { currencyField: 'shipping_currency', rateField: 'shipping_exchange_rate' },
    ] as const

    for (const column of currencyColumns) {
      const oldCurrency = String(row[column.currencyField] || 'EUR').toUpperCase()
      const newCurrency = String(patch[column.currencyField] || oldCurrency).toUpperCase()
      const rate = rateForCurrency(newCurrency)

      if (newCurrency === 'EUR') {
        patch[column.rateField] = 1
      } else if (rate !== null) {
        patch[column.rateField] = rate
      } else if (newCurrency !== oldCurrency) {
        redirect(`/admin/articoli/archivio?error=${encodeURIComponent(`Inserisci il cambio per ${newCurrency} prima di applicarlo.`)}`)
      }
    }

    if (Object.keys(patch).length === 0) continue
    const { error } = await supabase.from('articles').update(patch).eq('id', row.id)
    if (error) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(error.message)}`)

    await supabase.from('movements').insert({
      movement_type: 'MODIFICA',
      reference_id: row.id,
      reference_code: row.article_code,
      article_id: row.id,
      description: 'Costi articolo modificati in blocco',
      operator_user_id: user.id,
    })
  }

  revalidatePath('/admin/articoli/archivio')
  redirect('/admin/articoli/archivio?message=Costi e cambi valuta aggiornati correttamente.')
}

export async function deleteSelectedArticles(formData: FormData) {
  const { supabase } = await assertAdmin()
  const ids = String(formData.get('article_ids') || '').split(',').map((x) => x.trim()).filter(Boolean)
  if (!ids.length) redirect('/admin/articoli/archivio?error=Nessun articolo selezionato.')
  if (text(formData, 'confirm') !== '1') redirect('/admin/articoli/archivio?error=Conferma cancellazione richiesta.')

  const { error } = await supabase.rpc('admin_delete_articles', { p_article_ids: ids })
  if (error) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(error.message)}`)
  redirect('/admin/articoli/archivio?message=Articoli cancellati correttamente.')
}
