'use server'

import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { createClient } from '../../../lib/supabase-server'

const num = (formData: FormData, key: string, fallback = 0) => {
  const value = Number(formData.get(key) ?? fallback)
  return Number.isFinite(value) ? value : fallback
}

const text = (formData: FormData, key: string) => String(formData.get(key) || '').trim()


async function assertAdmin() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')
  const { data: profile } = await supabase.from('profiles').select('role').eq('user_id', user.id).maybeSingle()
  if (profile?.role !== 'AMMINISTRATORE') redirect('/dashboard')
  return { supabase, user }
}

const articlePayload = (formData: FormData) => {
  const quantity = num(formData, 'quantity_purchased')
  return {
    purchase_date: text(formData, 'purchase_date') || new Date().toISOString().slice(0, 10),
    origin: text(formData, 'origin') || 'GIAPPONE',
    article_type: text(formData, 'article_type') || 'ALTRO',
    seller: text(formData, 'seller') || null,
    series: text(formData, 'series') || null,
    detail: text(formData, 'detail') || null,
    quantity_purchased: quantity,
    currency: text(formData, 'currency') || 'EUR',
    unit_price_foreign: num(formData, 'unit_price_foreign'),
    exchange_rate: num(formData, 'exchange_rate', 1),
    commission_type: text(formData, 'commission_mode') || 'FIXED',
    commission_cost: num(formData, 'commission_cost'),
    commission_percent: num(formData, 'commission_percent'),
    commission_currency: text(formData, 'commission_currency') || 'EUR',
    commission_exchange_rate: num(formData, 'commission_exchange_rate', 1),
    customs_type: text(formData, 'customs_mode') || 'PERCENT',
    customs_cost: num(formData, 'customs_cost'),
    customs_percent: num(formData, 'customs_percent'),
    customs_currency: text(formData, 'customs_currency') || 'EUR',
    customs_exchange_rate: num(formData, 'customs_exchange_rate', 1),
    shipping_type: text(formData, 'shipping_mode') || 'FIXED',
    shipping_cost: num(formData, 'shipping_cost'),
    shipping_percent: num(formData, 'shipping_percent'),
    shipping_currency: text(formData, 'shipping_currency') || 'EUR',
    shipping_exchange_rate: num(formData, 'shipping_exchange_rate', 1),
    // I campi total_cost_eur e unit_cost_eur sono GENERATED BY DATABASE: non vanno inviati nell'INSERT/UPDATE.
    accessory_cost_eur: 0,
    // photo_url viene gestito separatamente durante creazione/modifica
    notes: text(formData, 'notes') || null,
    status: text(formData, 'status') || 'IN_ARRIVO',
  }
}

export async function createArticle(formData: FormData) {
  const { supabase } = await assertAdmin()
  const quantity = num(formData, 'quantity_purchased')
  if (quantity <= 0) redirect('/admin/articoli/nuovo?error=La quantità deve essere maggiore di zero.')

  const photo = formData.get('photo')
  const directPhotoUrl = text(formData, 'photo_url')
  if (photo instanceof File && photo.size > 0) {
    if (!photo.type.startsWith('image/')) redirect('/admin/articoli/nuovo?error=Il file selezionato non è una foto valida.')
    if (photo.size > 8 * 1024 * 1024) redirect('/admin/articoli/nuovo?error=La foto supera il limite di 8 MB.')
  }

  const payload = articlePayload(formData)
  const saleEnabled = text(formData, 'sale_enabled') === 'on'
  const saleCustomerCode = saleEnabled ? text(formData, 'sale_customer_code').toUpperCase() : ''
  const saleQuantity = saleEnabled ? num(formData, 'sale_quantity') : 0
  const salePrice = saleEnabled ? num(formData, 'sale_price') : 0
  const movementDate = text(formData, 'purchase_date') || new Date().toISOString().slice(0, 10)
  const exchangeRate = Number(payload.exchange_rate || 0)
  const accessoryRates = [payload.commission_exchange_rate, payload.customs_exchange_rate, payload.shipping_exchange_rate].map(Number)
  if (!Number.isFinite(exchangeRate) || exchangeRate <= 0 || accessoryRates.some((value) => !Number.isFinite(value) || value <= 0)) {
    redirect('/admin/articoli/nuovo?error=Uno o più cambi valuta non sono validi.')
  }

  if (saleEnabled && (!saleCustomerCode || !saleQuantity || saleQuantity <= 0 || !salePrice || salePrice <= 0 || saleQuantity > quantity)) {
    redirect('/admin/articoli/nuovo?error=Dati della vendita contestuale non validi.')
  }

  type ArticleResult = { id: string; article_code: string; quantity_purchased: number; total_cost_eur: number | null; status: string }
  let article: ArticleResult | null = null
  const rpcResult = await supabase.rpc('admin_create_article', { p_article: payload })

  if (rpcResult.data) {
    article = rpcResult.data as ArticleResult
  } else if (rpcResult.error) {
    // L'RPC è transazionale: in caso di errore non lascia un articolo parzialmente registrato.
    // Usiamo quindi un fallback diretto per gestire eventuale disallineamento della schema cache.
    const rpcMessage = rpcResult.error.message || 'Impossibile registrare l articolo.'

    // Fallback per ambienti in cui PostgREST non ha ancora aggiornato la cache RPC.
    const { data: directArticle, error: directError } = await supabase
      .from('articles')
      .insert(payload)
      .select('id,article_code,quantity_purchased,total_cost_eur,status')
      .single()

    if (directError || !directArticle) {
      redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(directError?.message || rpcMessage)}`)
    }

    const { error: movementError } = await supabase.from('movements').insert({
      movement_type: 'ARTICOLO',
      reference_id: directArticle.id,
      reference_code: directArticle.article_code,
      article_id: directArticle.id,
      quantity: Number(directArticle.quantity_purchased || 0),
      total_amount_eur: Number(directArticle.total_cost_eur || 0),
      description: 'Creazione articolo',
      operator_user_id: (await supabase.auth.getUser()).data.user?.id || null,
      movement_at: `${payload.purchase_date}T00:00:00`,
    })

    if (movementError) {
      await supabase.from('articles').delete().eq('id', directArticle.id)
      redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Registrazione movimento non riuscita: ${movementError.message}`)}`)
    }

    article = directArticle as ArticleResult
  }

  if (!article) {
    redirect('/admin/articoli/nuovo?error=Impossibile registrare l articolo.')
  }

  if (photo instanceof File && photo.size > 0) {
    if (!photo.type.startsWith('image/')) redirect('/admin/articoli/nuovo?error=Il file selezionato non è una foto valida.')
    if (photo.size > 8 * 1024 * 1024) redirect('/admin/articoli/nuovo?error=La foto supera il limite di 8 MB.')
    const extension = photo.name.split('.').pop()?.toLowerCase() || 'jpg'
    const path = `${article.id}-${Date.now()}.${extension}`
    const { error: uploadError } = await supabase.storage.from('article-photos').upload(path, photo, { contentType: photo.type, upsert: true })
    if (uploadError) redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Caricamento foto non riuscito: ${uploadError.message}. Verifica che l'app punti al progetto Supabase corretto e che il bucket article-photos sia disponibile.`)}`)
    const { data: publicData } = supabase.storage.from('article-photos').getPublicUrl(path)
    await supabase.from('articles').update({ photo_url: publicData.publicUrl }).eq('id', article.id)
  } else if (directPhotoUrl) {
    await supabase.from('articles').update({ photo_url: directPhotoUrl }).eq('id', article.id)
  }

  if (saleEnabled) {
    const { error: saleError } = await supabase.rpc('register_article_sales', {
      p_customer_code: saleCustomerCode,
      p_lines: [{ article_id: article.id, quantity: saleQuantity, price: salePrice }],
      p_movement_date: movementDate,
    })
    if (saleError) {
      await supabase.rpc('admin_delete_articles', { p_article_ids: [article.id] })
      redirect(`/admin/articoli/nuovo?error=${encodeURIComponent(`Vendita contestuale non registrata: ${saleError.message}`)}`)
    }
  }

  revalidatePath('/admin/articoli/archivio')
  revalidatePath('/admin/articoli/nuovo')
  redirect('/admin/articoli/archivio?message=Articolo registrato correttamente.')
}

export async function updateArticle(formData: FormData) {
  const { supabase } = await assertAdmin()
  const id = text(formData, 'id')
  if (!id) redirect('/admin/articoli?error=ID articolo mancante.')

  const quantity = num(formData, 'quantity_purchased')
  if (quantity <= 0) redirect(`/admin/articoli/${id}?error=La quantità deve essere maggiore di zero.`)

  const payload = articlePayload(formData)
  const directPhotoUrl = text(formData, 'photo_url')
  const photo = formData.get('photo')
  let photoPatch: Record<string, string | null> = {}
  if (photo instanceof File && photo.size > 0) {
    if (!photo.type.startsWith('image/') || photo.size > 8 * 1024 * 1024) redirect(`/admin/articoli/${id}?error=Foto non valida o superiore a 8 MB.`)
    const extension = photo.name.split('.').pop()?.toLowerCase() || 'jpg'
    const path = `${id}-${Date.now()}.${extension}`
    const { error: uploadError } = await supabase.storage.from('article-photos').upload(path, photo, { contentType: photo.type, upsert: true })
    if (uploadError) redirect(`/admin/articoli/${id}?error=${encodeURIComponent(`Caricamento foto non riuscito: ${uploadError.message}. Verifica che l'app punti al progetto Supabase corretto e che il bucket article-photos sia disponibile.`)}`)
    const { data: publicData } = supabase.storage.from('article-photos').getPublicUrl(path)
    photoPatch = { photo_url: publicData.publicUrl }
  } else if (directPhotoUrl) {
    photoPatch = { photo_url: directPhotoUrl }
  }
  const { error } = await supabase.from('articles').update({ ...payload, ...photoPatch }).eq('id', id)
  if (error) redirect(`/admin/articoli/${id}?error=${encodeURIComponent(error.message)}`)

  await supabase.from('movements').insert({
    movement_type: 'MODIFICA',
    reference_id: id,
    reference_code: id,
    article_id: id,
    description: 'Articolo modificato',
    operator_user_id: (await supabase.auth.getUser()).data.user?.id || null,
  })

  redirect(`/admin/articoli/${id}?message=Modifiche salvate correttamente.`)
}


export async function updateSelectedArticles(formData: FormData) {
  const { supabase } = await assertAdmin()
  const ids = String(formData.get('article_ids') || '').split(',').map((x) => x.trim()).filter(Boolean)
  if (!ids.length) redirect('/admin/articoli/archivio?error=Nessun articolo selezionato.')

  const bulkCustomsRaw = text(formData, 'bulk_customs_cost')
  const bulkCustomsCurrency = text(formData, 'bulk_customs_currency').toUpperCase()
  const bulkShippingRaw = text(formData, 'bulk_shipping_cost')
  const bulkShippingCurrency = text(formData, 'bulk_shipping_currency').toUpperCase()
  const bulkExchangeRaw = text(formData, 'bulk_exchange_rate')

  const bulkCustoms = bulkCustomsRaw === '' ? null : Number(bulkCustomsRaw)
  const bulkShipping = bulkShippingRaw === '' ? null : Number(bulkShippingRaw)
  const bulkExchange = bulkExchangeRaw === '' ? null : Math.round(Number(bulkExchangeRaw))

  if (bulkCustoms !== null && (!Number.isFinite(bulkCustoms) || bulkCustoms < 0)) {
    redirect('/admin/articoli/archivio?error=Valore DOGANA non valido.')
  }
  if (bulkShipping !== null && (!Number.isFinite(bulkShipping) || bulkShipping < 0)) {
    redirect('/admin/articoli/archivio?error=Valore SPEDIZIONE non valido.')
  }
  if (bulkExchange !== null && (!Number.isFinite(bulkExchange) || bulkExchange < 1)) {
    redirect('/admin/articoli/archivio?error=CAMBIO VALUTA non valido.')
  }
  if (bulkCustomsCurrency && !/^[A-Z0-9]{2,8}$/.test(bulkCustomsCurrency)) {
    redirect('/admin/articoli/archivio?error=Valuta dogana non valida.')
  }
  if (bulkShippingCurrency && !/^[A-Z0-9]{2,8}$/.test(bulkShippingCurrency)) {
    redirect('/admin/articoli/archivio?error=Valuta spedizione non valida.')
  }

  const { data: sales } = await supabase
    .from('movements')
    .select('article_id,quantity')
    .eq('movement_type', 'VENDITA')
    .in('article_id', ids)

  const soldById = new Map<string, number>()
  for (const row of sales || []) {
    if (!row.article_id) continue
    soldById.set(row.article_id, (soldById.get(row.article_id) || 0) + Number(row.quantity || 0))
  }

  for (const id of ids) {
    const quantity = num(formData, `quantity_${id}`)
    const unitPrice = num(formData, `unit_price_${id}`)
    const accessory = num(formData, `accessory_cost_${id}`)
    const sold = soldById.get(id) || 0
    if (quantity < Math.max(1, sold) || unitPrice < 0 || accessory < 0) {
      redirect(`/admin/articoli/archivio?error=${encodeURIComponent(`Dati non validi per l'articolo ${id}.`)}`)
    }

    const { data: current } = await supabase
      .from('articles')
      .select('quantity_purchased')
      .eq('id', id)
      .maybeSingle()
    if (!current) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(`Articolo ${id} non trovato.`)}`)

    const patch: Record<string, unknown> = {
      unit_price_foreign: unitPrice,
      quantity_purchased: quantity,
      accessory_cost_eur: accessory,
    }

    if (bulkExchange !== null) {
      patch.exchange_rate = bulkExchange
      patch.customs_exchange_rate = bulkExchange
      patch.shipping_exchange_rate = bulkExchange
    }
    if (bulkCustoms !== null) {
      patch.customs_type = 'FIXED'
      patch.customs_cost = bulkCustoms
      patch.customs_percent = 0
    }
    if (bulkCustomsCurrency) patch.customs_currency = bulkCustomsCurrency
    if (bulkShipping !== null) {
      patch.shipping_type = 'FIXED'
      patch.shipping_cost = bulkShipping
      patch.shipping_percent = 0
    }
    if (bulkShippingCurrency) patch.shipping_currency = bulkShippingCurrency

    const { error } = await supabase.from('articles').update(patch).eq('id', id)
    if (error) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(error.message)}`)

    const photoUrl = String(formData.get(`photo_url_${id}`) || '').trim()
    const photo = formData.get(`photo_${id}`)
    if (photo instanceof File && photo.size > 0) {
      if (!photo.type.startsWith('image/') || photo.size > 8 * 1024 * 1024) redirect(`/admin/articoli/archivio?error=${encodeURIComponent('Foto non valida o superiore a 8 MB.')}`)
      const extension = photo.name.split('.').pop()?.toLowerCase() || 'jpg'
      const path = `${id}-${Date.now()}.${extension}`
      const { error: uploadError } = await supabase.storage.from('article-photos').upload(path, photo, { contentType: photo.type, upsert: true })
      if (uploadError) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(`Caricamento foto non riuscito: ${uploadError.message}. Verifica che l'app punti al progetto Supabase corretto e che il bucket article-photos sia disponibile.`)}`)
      const { data: publicData } = supabase.storage.from('article-photos').getPublicUrl(path)
      const { error: photoError } = await supabase.from('articles').update({ photo_url: publicData.publicUrl }).eq('id', id)
      if (photoError) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(photoError.message)}`)
    } else if (photoUrl) {
      try { new URL(photoUrl) } catch { redirect(`/admin/articoli/archivio?error=${encodeURIComponent(`Link immagine non valido per l'articolo ${id}.`)}`) }
      const { error: photoError } = await supabase.from('articles').update({ photo_url: photoUrl }).eq('id', id)
      if (photoError) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(photoError.message)}`)
    }
  }

  redirect('/admin/articoli/archivio?message=Articoli modificati correttamente.')
}

export async function deleteSelectedArticles(formData: FormData) {
  const { supabase } = await assertAdmin()
  const ids = String(formData.get('article_ids') || '').split(',').map((x) => x.trim()).filter(Boolean)
  if (!ids.length) redirect('/admin/articoli/archivio?error=Nessun articolo selezionato.')
  if (text(formData, 'confirm') !== '1') redirect('/admin/articoli/archivio?error=Conferma cancellazione richiesta.')

  const { error } = await supabase.rpc('admin_delete_articles', { p_article_ids: ids })
  if (error) redirect(`/admin/articoli/archivio?error=${encodeURIComponent(error.message)}`)
  redirect('/admin/articoli/archivio?message=Articoli cancellati correttamente.')
}
